name: Update NBViewer Links Workflow

on:
  push:
    branches:
      - master  # You can specify the branch you want to trigger this workflow on
permissions:
  contents: write
jobs:
  update_links:
    runs-on: ubuntu-latest  # You can choose the appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Update NBViewer Links
      uses: KensingtonOscupant/nbviewer-flush-cache-action@v1.0.4
      with:
        file_path: 'master/420-SN1-RE_ProgSciencesNat/Cours_1cours_1.ipynb'  # IMPORTANT! path to the file where you would like to have the links changed, for the readme it would be 'README.md'

